analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3495119,"name"\:"OrangeHRM Trial \#3495119","teamId"\:3488964,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3506621,"accountId"\:null,"autoIntegrate"\:false,"sampleProject"\:false}
analytics.team={"id"\:3488964,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
